### ISSUE TITLE
Dogecoinj orchid?

### ISSUE THREAD

**Issue by whitj00** [langerhans/dogecoinj-new#14]
[ERROR] Failed to execute goal on project dogecoinj-core: Could not resolve dependencies for project com.dogecoin:dogecoinj-core:jar:0.13-SNAPSHOT: Failure to find com.dogecoin:orchid:jar:1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by langerhans** [comment]
Did you get it resolved with the info from IRC? Orchid is there in the tree, you just have to `mvn clean install` it.

**Comment by whitj00** [comment]
[INFO] Building dogecoinj 0.13-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/com/dogecoin/orchid/1.1/orchid-1.1.pom
[WARNING] The POM for com.dogecoin:orchid:jar:1.1 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/dogecoin/orchid/1.1/orchid-1.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dogecoinj Parent ................................... SUCCESS [  0.534 s]
[INFO] dogecoinj .......................................... FAILURE [  2.359 s]
[INFO] dogecoinj Examples ................................. SKIPPED
[INFO] dogecoinj Tools .................................... SKIPPED
[INFO] dogecoinj Wallet-Template .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.084 s
[INFO] Finished at: 2015-03-06T11:40:17-08:00
[INFO] Final Memory: 19M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dogecoinj-core: Could not resolve dependencies for project com.dogecoin:dogecoinj-core:jar:0.13-SNAPSHOT: Could not find artifact com.dogecoin:orchid:jar:1.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dogecoinj-core
whit:dogecoinj-new whit$

**Comment by langerhans** [comment]
I mean `cd orchid && mvn clean install`, then go back to dogecoinj and `mvn clean install -DskipTests`
