### ISSUE TITLE
Orchid different hash for different builds

### ISSUE THREAD

**Issue by afwang** [langerhans/dogecoinj-new#15]
Whenever I build Orchid, I get a different hash than the expected hash in the pom. This leads to this error when I try to build Dogecoinj:

    [ERROR] *** CRITICAL FAILURE *** Artifact does not match. Possible dependency-chain attack.
    Expected='393d53cad40f32f1c00a717326deeb4bde8ee57b'
    Actual='4f8464b36b2965e066f812e9b82aa031ad72ef2a'

Is there a quick, simple way to build the orchid dependency so it becomes the same jar each and every time, or is changing the hash for the urn entry in the pom the simplest (which I don't think should be a good idea)?

**Comment by langerhans** [comment]
Odd, I just built and suddenly got the exact same error. Maybe a dependency changed, but I don't think that would be a big issue. I don't see a big problem in just editing the hash in the urn entry. There are afaik no Tor based Dogecoin nodes anyway, so Orchid is not actually in use.

**Comment by afwang** [comment]
I see. I'd like to help getting the wallet into the F-Droid repos. I see the DogecoinJ library metadata text file is already in the fdroiddata repository, but I'm not sure how we can include that library if the hash changes with every build.

**Comment by langerhans** [comment]
I can locally verify the Orchid build and commit the correct hash. It might just be an upstream change that  I missed since I didn't recently re-build Orchid. 
I've looked into fdroid before, but my issue was getting the native scrypt libraries automatically built. I have almost no experience with the Android NDK, so even that build I did once took me hours to get running locally. If you could get that running, it would be awesome of course. Afaik fdroid wouldn't allow a precompiled binary by definition, right?

**Comment by afwang** [comment]
Right, F-droid requires everything must be built from source.

I reread my opening comment, and I need to add some clarification. It's not that orchid's hash is different the hash in the pom.xml. The hash is different for every single build of Orchid.

For example, just after rebuilding Orchid now with no changes to source or the pom, I run into the same error again:

    [ERROR] *** CRITICAL FAILURE *** Artifact does not match. Possible dependency-chain attack. 
    Expected='4f8464b36b2965e066f812e9b82aa031ad72ef2a'
    Actual='367380c422a28342070ea7dff856d4b27413cdf3'

The expected value is different since I changed it in the pom yesterday just to get a sample wallet build running, but you'll see that the actual hash is also different from the original expected value (which would be 393d53cad40f32f1c00a717326deeb4bde8ee57b).

If I rebuild orchid again and then check its hash, I see it's now

    75e5dd789ef69902304a9bf33395acdd121ea5c1

I believe this is because the archive tool adds the files' last modified times to the archive, and pom.properties records the build time for each build.

Since we're building orchid locally, would it make sense to remove the urn entry for orchid from core/pom.xml, but add in urn entries for dependencies into orchid/pom.xml?

**Comment by langerhans** [comment]
I was wondering how upstream handles that and then remembered that they distribute with Maven Ctral, so also their Orchif build is there, working around the determinism issue (http://mvnrepository.com/artifact/org.bitcoinj/orchid)  

>Since we're building orchid locally, would it make sense to remove the urn entry for orchid from core/pom.xml, but add in urn entries for dependencies into orchid/pom.xml? If this is the case, I'd like to get my hands dirty and try contributing.  

That seems like a reasonable workaround for the non-determinism. Seen as it doesn't have many dependencies. Would appreciate if you want to contribute. Just ping me if you need anything. I also regularly hang out at freedone/#dogecoin-dev in case you want to have a chat :)

**Comment by afwang** [comment]
Sure! I'll send in a request around the weekend. See you then.

**Comment by langerhans** [comment]
Just fyi that I go on vacation next week, so I might not be able to merge it right away :)

**Comment by afwang** [comment]
Looks like we're both pretty busy then. I guess we'll take this slowly and steadily.

**Comment by langerhans** [comment]
Closed with merge of #16
